apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  labels:
    app: redis-leader
    role: leader
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-leader
    role: leader
    tier: backend
